// Guards the string catalog generated by `python tool/gen_i18n.py`.
//
// The previous app_strings.dart was a map per language, so adding a string
// meant editing nine separate places and a missed one was invisible. It listed
// Gujarati as a supported language and had no Gujarati map at all, so every
// Gujarati merchant silently got English while the picker showed a tick next
// to their language. These tests make that class of gap a build failure.

import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:kamaiplus_pos/core/localization/app_strings.dart';
import 'package:kamaiplus_pos/core/localization/app_language_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() => SharedPreferences.setMockInitialValues({}));

  group('Catalog completeness', () {
    test('every supported language has a real translation for every key', () {
      final missing = <String>[];

      for (final key in AppStrings.allKeys) {
        final english = AppStrings.get(key, lang: 'en');
        for (final lang in AppStrings.supportedLanguages) {
          final value = AppStrings.get(key, lang: lang.code);
          if (value.isEmpty || value == key) {
            missing.add('${lang.code}/$key (empty)');
          } else if (lang.code != 'en' && value == english) {
            // Genuinely-identical strings exist (UPI, MRP), so this is only a
            // signal when a whole language is echoing English.
            missing.add('${lang.code}/$key (same as English)');
          }
        }
      }

      // Acronyms that are the same everywhere.
      final realMissing = missing
          .where((m) => !m.contains('/upi') && !m.contains('/mrp'))
          .toList();

      expect(realMissing, isEmpty,
          reason: 'Run `python tool/gen_i18n.py` after adding the missing '
              'translations to tool/i18n_data.py:\n${realMissing.take(20).join('\n')}');
    });

    test('all nine languages are declared', () {
      expect(AppStrings.supportedLanguages.length, 9);
      final codes = AppStrings.supportedLanguages.map((l) => l.code).toSet();
      for (final c in ['en', 'hi', 'mr', 'gu', 'ta', 'te', 'kn', 'bn', 'pa']) {
        expect(codes.contains(c), isTrue, reason: '$c missing from the picker');
      }
    });

    test('the catalog is not trivially small', () {
      // A guard against a regeneration that silently produced an empty map.
      expect(AppStrings.allKeys.length, greaterThanOrEqualTo(100));
    });
  });

  group('Language metadata', () {
    test('English, Hindi and Marathi are NOT marked beta', () {
      // These three are reviewable by the team, so they carry no caveat.
      for (final code in ['en', 'hi', 'mr']) {
        expect(AppStrings.languageFor(code).isBeta, isFalse, reason: code);
      }
    });

    test('the six unreviewed languages ARE marked beta', () {
      for (final code in ['gu', 'ta', 'te', 'kn', 'bn', 'pa']) {
        expect(AppStrings.languageFor(code).isBeta, isTrue,
            reason: '$code has not been reviewed by a speaker and must say so');
      }
    });

    test('every language has an Indian TTS locale for the soundbox', () {
      for (final l in AppStrings.supportedLanguages) {
        expect(l.ttsLocale.endsWith('-IN'), isTrue, reason: l.code);
        expect(l.ttsLocale.startsWith(l.code), isTrue, reason: l.code);
      }
    });

    test('each language shows its own name in its own script', () {
      for (final l in AppStrings.supportedLanguages) {
        expect(l.nativeName.trim(), isNotEmpty);
      }
      // A merchant who cannot read English finds their language by its own
      // name, so these must not all be Latin.
      expect(AppStrings.languageFor('hi').nativeName, 'हिंदी');
      expect(AppStrings.languageFor('ta').nativeName, 'தமிழ்');
      expect(AppStrings.languageFor('bn').nativeName, 'বাংলা');
    });
  });

  group('Lookup behaviour', () {
    test('an unknown key returns itself, not a blank', () {
      // A screen showing "checkout_v2" is a bug report; a blank is a mystery.
      expect(AppStrings.get('no_such_key_anywhere', lang: 'hi'), 'no_such_key_anywhere');
    });

    test('an unknown language falls back to English rather than breaking', () {
      expect(AppStrings.get('nav_home', lang: 'zz'), AppStrings.get('nav_home', lang: 'en'));
    });

    test('known keys resolve in each verifiable language', () {
      expect(AppStrings.get('nav_home', lang: 'en'), 'Home');
      expect(AppStrings.get('nav_home', lang: 'hi'), 'होम');
      expect(AppStrings.get('language', lang: 'mr'), 'भाषा');
    });
  });

  group('AppLanguageService', () {
    test('defaults to English', () async {
      await AppLanguageService.instance.init();
      expect(AppLanguageService.instance.currentLanguage, 'en');
    });

    test('a chosen language persists across a restart', () async {
      await AppLanguageService.instance.setLanguage('mr');
      expect(AppLanguageService.instance.currentLanguage, 'mr');

      // Simulate a fresh launch reading the same store.
      AppLanguageService.instance.currentLanguageNotifier.value = 'en';
      await AppLanguageService.instance.init();
      expect(AppLanguageService.instance.currentLanguage, 'mr');
    });

    test('an unsupported code is ignored rather than blanking the app', () async {
      await AppLanguageService.instance.setLanguage('hi');
      await AppLanguageService.instance.setLanguage('klingon');
      expect(AppLanguageService.instance.currentLanguage, 'hi');
    });

    test('switching language is synchronous for readers', () async {
      // The notifier flips before the async write completes, which is what
      // makes the UI swap instantly instead of waiting on disk.
      await AppLanguageService.instance.setLanguage('ta');
      expect(AppLanguageService.instance.t('nav_home'), AppStrings.get('nav_home', lang: 'ta'));
    });

    test('the TTS locale follows the chosen language', () async {
      await AppLanguageService.instance.setLanguage('bn');
      expect(AppLanguageService.instance.ttsLocale, 'bn-IN');
      await AppLanguageService.instance.setLanguage('en');
      expect(AppLanguageService.instance.ttsLocale, 'en-IN');
    });

    test('beta status is exposed for the active language', () async {
      await AppLanguageService.instance.setLanguage('hi');
      expect(AppLanguageService.instance.isBetaLanguage, isFalse);
      await AppLanguageService.instance.setLanguage('te');
      expect(AppLanguageService.instance.isBetaLanguage, isTrue);
    });

    test('the .tr extension reads the active language', () async {
      await AppLanguageService.instance.setLanguage('hi');
      expect('nav_home'.tr, 'होम');
      await AppLanguageService.instance.setLanguage('en');
      expect('nav_home'.tr, 'Home');
    });
  });
}
