org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.20.101-hotspot
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
